name: Devato
favicon: null
layout_spectrum: 0.9372075158171356
typography_spectrum: 0.3845316374208778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6223949072882533
  lightness: 0.05334095726720989
  saturation: 0.662916621658951
  rhythmicContrast: 0.23832611134275794
purpose: []
